version: '3.4'

networks:
   blogapp-dev:
      driver: bridge

services:
    blogapp:
      image: blogapp:latest
      depends_on:
          - "sql-server-db"
      build:
         context: .
         dockerfile: Dockerfile
      ports:
         - "5000:80"
      environment:
        DB_CONNECTION_STRING: "Server=sql-server-db;Database=blogdb;User=sa;Password=Jokoyoski200@"
      
      networks:
        - blogapp-dev

    sql-server-db:

     container_name: sql-server-db

     image: microsoft/mssql-server-linux:2017-latest

     ports:
       - "1433:1433"

     environment:
        SA_PASSWORD: "Jokoyoski200@"
        ACCEPT_EULA: "Y"

     networks:
        - blogapp-dev
